# -*- mode: org; fill-column: 78; -*-
# Time-stamp: <2025-07-30 19:21:06 krylon>
#+TAGS: internals(i) ui(u) bug(b) feature(f)
#+TAGS: database(d) design(e), meditation(m)
#+TAGS: optimize(o) refactor(r) cleanup(c)
#+TODO: TODO(t)  RESEARCH(r) IMPLEMENT(i) TEST(e) | DONE(d) FAILED(f) CANCELLED(c)
#+TODO: MEDITATE(m) PLANNING(p) | SUSPENDED(s)
#+PRIORITIES: A G D

* Care Bear [5/7]
  :PROPERTIES:
  :COOKIE_DATA: todo recursive
  :VISIBILITY: children
  :END:
** Clocktable
   #+BEGIN: clocktable :scope file :maxlevel 255 :emphasize t
   #+CAPTION: Clock summary at [2025-07-26 Sa 18:10]
   | Headline                                    | Time       |            |         |      |
   |---------------------------------------------+------------+------------+---------+------|
   | *Total time*                                | *2d 13:35* |            |         |      |
   |---------------------------------------------+------------+------------+---------+------|
   | *Care Bear [5/7]*                           | *2d 13:35* |            |         |      |
   | \_  /Components [5/7]/                      |            | /2d 13:35/ |         |      |
   | \_    Model [1/1]                           |            |            |    0:28 |      |
   | \_      Test IP enumeration                 |            |            |         | 0:28 |
   | \_    Database [0/1]                        |            |            |    3:53 |      |
   | \_    Scanner [2/2]                         |            |            |    9:55 |      |
   | \_      Make progress of scan more visible  |            |            |         | 1:28 |
   | \_      Make number of workers configurable |            |            |         | 0:24 |
   | \_    Probe [2/2]                           |            |            |    8:54 |      |
   | \_    Scheduler [0/0]                       |            |            | 1d 7:24 |      |
   | \_    Web UI [0/0]                          |            |            |    7:01 |      |
   #+END:
** Components [5/7]
*** Common [0/1]
**** TODO [#G] Make default log level configurable
*** Model [1/1]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: children
    :END:
    :LOGBOOK:
    CLOCK: [2025-07-11 Fr 14:50]--[2025-07-11 Fr 14:50] =>  0:00
    :END:
**** DONE Test IP enumeration
     CLOSED: [2025-07-11 Fr 15:18]
     :LOGBOOK:
     CLOCK: [2025-07-11 Fr 14:50]--[2025-07-11 Fr 15:18] =>  0:28
     :END:
*** Database [1/2]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: children
    :END:
    :LOGBOOK:
    CLOCK: [2025-07-08 Di 18:42]--[2025-07-08 Di 19:51] =>  1:09
    CLOCK: [2025-07-07 Mo 14:49]--[2025-07-07 Mo 16:08] =>  1:19
    CLOCK: [2025-07-07 Mo 14:40]--[2025-07-07 Mo 14:48] =>  0:08
    CLOCK: [2025-07-05 Sa 14:48]--[2025-07-05 Sa 15:44] =>  0:56
    CLOCK: [2025-07-04 Fr 14:54]--[2025-07-04 Fr 15:15] =>  0:21
    :END:
**** DONE Extend schema
     CLOSED: [2025-07-30 Mi 19:19]
     :LOGBOOK:
     CLOCK: [2025-07-30 Mi 18:31]--[2025-07-30 Mi 19:19] =>  0:48
     :END:
     Right now ([2025-07-30 Mi]), the database only stores networks and
     devices, I obviously want to store more than that. Let's get to it.
**** TODO More verbose logging
*** Scanner [3/3]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: children
    :END:
    :LOGBOOK:
    CLOCK: [2025-07-30 Mi 17:37]--[2025-07-30 Mi 17:37] =>  0:00
    CLOCK: [2025-07-12 Sa 17:13]--[2025-07-12 Sa 18:10] =>  0:57
    CLOCK: [2025-07-11 Fr 15:19]--[2025-07-11 Fr 17:21] =>  2:02
    CLOCK: [2025-07-10 Do 15:20]--[2025-07-10 Do 16:27] =>  1:07
    CLOCK: [2025-07-09 Mi 14:02]--[2025-07-09 Mi 14:27] =>  0:25
    CLOCK: [2025-07-08 Di 20:00]--[2025-07-08 Di 22:30] =>  2:30
    CLOCK: [2025-07-08 Di 14:37]--[2025-07-08 Di 15:33] =>  0:56
    CLOCK: [2025-07-08 Di 11:51]--[2025-07-08 Di 11:57] =>  0:06
    :END:
    I should look into https://github.com/korylprince/ipnetgen to enumerate or
    iterate over all addresses in a network.
**** DONE Add a way to scan a specific network
     CLOSED: [2025-07-30 Mi 18:30]
     :LOGBOOK:
     CLOCK: [2025-07-30 Mi 17:37]--[2025-07-30 Mi 18:30] =>  0:53
     :END:
     I think I might need to rewrite the public interface of the Scanner.
**** DONE Make progress of scan more visible
     CLOSED: [2025-07-12 Sa 20:02]
     :LOGBOOK:
     CLOCK: [2025-07-12 Sa 18:34]--[2025-07-12 Sa 20:02] =>  1:28
     :END:
**** DONE Make number of workers configurable
     CLOSED: [2025-07-12 Sa 18:34]
     :LOGBOOK:
     CLOCK: [2025-07-12 Sa 18:10]--[2025-07-12 Sa 18:34] =>  0:24
     :END:
*** Probe [2/2]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: children
    :END:
    :LOGBOOK:
    CLOCK: [2025-07-26 Sa 16:22]--[2025-07-26 Sa 16:41] =>  0:19
    CLOCK: [2025-07-23 Mi 21:46]--[2025-07-23 Mi 22:48] =>  1:02
    CLOCK: [2025-07-23 Mi 19:47]--[2025-07-23 Mi 20:53] =>  1:06
    CLOCK: [2025-07-22 Di 17:22]--[2025-07-22 Di 20:23] =>  3:01
    CLOCK: [2025-07-22 Di 14:23]--[2025-07-22 Di 15:35] =>  1:12
    CLOCK: [2025-07-21 Mo 15:40]--[2025-07-21 Mo 17:54] =>  2:14
    :END:
**** DONE Connect via SSH
     CLOSED: [2025-07-22 Di 18:12]
     If possible with public key authentication.
**** DONE Query OS
     CLOSED: [2025-07-22 Di 18:12]
*** Scheduler [0/0]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: children
    :END:
    :LOGBOOK:
    CLOCK: [2025-07-30 Mi 17:36]--[2025-07-30 Mi 17:37] =>  0:01
    CLOCK: [2025-07-26 Sa 16:41]--[2025-07-26 Sa 18:10] =>  1:29
    CLOCK: [2025-07-26 Sa 16:21]--[2025-07-26 Sa 16:22] =>  0:01
    CLOCK: [2025-07-24 Do 17:29]--[2025-07-25 Fr 23:23] => 29:54
    :END:
    I have been doing this wrong. The scheduler doesn't receive commands, it
    emits commands, if anything.
*** Web UI [0/0]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: children
    :END:
    :LOGBOOK:
    CLOCK: [2025-07-18 Fr 09:45]--[2025-07-18 Fr 10:40] =>  0:55
    CLOCK: [2025-07-17 Do 10:51]--[2025-07-17 Do 11:09] =>  0:18
    CLOCK: [2025-07-16 Mi 15:55]--[2025-07-16 Mi 16:50] =>  0:55
    CLOCK: [2025-07-15 Di 18:05]--[2025-07-15 Di 19:38] =>  1:33
    CLOCK: [2025-07-15 Di 17:12]--[2025-07-15 Di 17:43] =>  0:31
    CLOCK: [2025-07-14 Mo 17:32]--[2025-07-14 Mo 17:50] =>  0:18
    CLOCK: [2025-07-14 Mo 16:25]--[2025-07-14 Mo 17:04] =>  0:39
    CLOCK: [2025-07-14 Mo 14:26]--[2025-07-14 Mo 16:18] =>  1:52
    :END:
** Features [0/0]
** Bugs [0/0]
